/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.glassfish.jersey.jdkhttp.JdkHttpServerFactory;

public class App {
    public String getGreeting() {
        return "Hello World";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
